export const SLUG_CONFIGS = {
  // Rider-related slugs
  "top-rider-stage": {
    apiEndpoint: "stageTop10sRider",
    headers: ["NAME", "TEAM", "COUNT"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["stage_wins", "stageWins", "count", "total"],
    },
  },
  "most-racing-days": {
    apiEndpoint: "mostRacingDays",
    headers: ["NAME", "TEAM", "RACING DAYS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["racing_days", "racingDays", "count", "total"],
    },
  },
  "team-most-stage-wins": {
    apiEndpoint: "getTopStageRiders",
    headers: ["TEAM", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "flag"],
      count: ["wins", "stageWins", "count", "total"],
    },
  },
  "riders-with-birthday-today": {
    apiEndpoint: "ridersWithBirthdayToday",
    headers: ["NAME", "AGE"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "flag",
        "nationality",
      ],
      count: ["birthday", "birth_date", "count", "total", "age_today"],
    },
  },
  "team-with-most-rider": {
    apiEndpoint: "teamWithMostRider",
    headers: ["TEAM", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: [],
      country: ["team_country", "teamCountry", "country"],
      count: [
        "riders",
        "rider_count",
        "count",
        "total",
        "numberOfWinningRiders",
      ],
    },
  },
  "most-kms-raced": {
    apiEndpoint: "mostKMsRaced",
    headers: ["NAME", "TEAM", "KMS RACED"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "rider_key"],
      team: ["team_name", "teamName", "team", "team_name"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["kms_raced", "kmsRaced", "count", "total", "total_distance"],
    },
  },
  "most-wins": {
    apiEndpoint: "mostWin",
    headers: ["NAME", "TEAM", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "most-stage-wins": {
    apiEndpoint: "mostStageWins",
    headers: ["NAME", "TEAM", "STAGE WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["stage_wins", "stageWins", "count", "total"],
    },
  },
  "most-gc-wins": {
    apiEndpoint: "mostGCWins",
    headers: ["NAME", "TEAM", "GC WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["gc_wins", "gcWins", "count", "total"],
    },
  },
  "oldest-riders": {
    apiEndpoint: "oldestRider",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["age", "rider_age", "count", "total"],
    },
  },
  "youngest-riders-stats": {
    apiEndpoint: "youngestRider",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["age", "rider_age", "count", "total"],
    },
  },
  "most-dnfs": {
    apiEndpoint: "mostDNFs",
    headers: ["RACE NAME", "DNFS"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["country_code", "country", "rider_country", "riderCountry"],
      count: ["dnfs", "dnf_count", "count", "total"],
    },
  },
  "most-mountain-wins": {
    apiEndpoint: "mostmountainwins",
    headers: ["NAME", "TEAM", "MOUNTAIN WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: [
        "mountain_wins",
        "mountainWins",
        "count",
        "total",
        "totalKOMTitles",
      ],
    },
  },
  "most-sprint-wins": {
    apiEndpoint: "sprintWins",
    headers: ["NAME", "TEAM", "SPRINT WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["sprint_wins", "sprintWins", "count", "total"],
    },
  },
  "most-top5-no-wins": {
    apiEndpoint: "mostTop5Wins",
    headers: ["NAME", "TEAM", "TOP 5"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["top5_count", "top5Count", "count", "total"],
    },
  },
  "most-second-places": {
    apiEndpoint: "mostSecondPlaces",
    headers: ["NAME", "TEAM", "SECOND PLACES"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["second_place_count", "secondPlaces", "count", "total"],
    },
  },
  "riders-yet-to-start": {
    apiEndpoint: "ridersYetToStart",
    headers: ["NAME", "TEAM", "STATUS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["status", "race_status", "count", "total"],
    },
  },
  "best-classics": {
    apiEndpoint: "bestClassics",
    headers: ["NAME", "TEAM", "CLASSIC WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["classic_wins", "classicWins", "count", "total"],
    },
  },
  "oldest-most-wins": {
    apiEndpoint: "oldestMostWins",
    headers: ["NAME", "TEAM", "AGE", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["wins", "win_count", "count", "total"],
      age: ["age", "rider_age"],
    },
  },
  "youngest-most-wins": {
    apiEndpoint: "youngestMostWins",
    headers: ["NAME", "TEAM", "AGE", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["wins", "win_count", "count", "total"],
      age: ["age", "rider_age"],
    },
  },
  "oldest-active-riders": {
    apiEndpoint: "olderstRiders",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["wins", "win_count", "count", "total"],
      age: ["age", "rider_age"],
    },
  },
  "lightest-rider": {
    apiEndpoint: "lightestRider",
    headers: ["NAME", "WEIGHT"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["weight", "rider_weight", "count", "total"],
    },
  },
  "most-weight-riders": {
    apiEndpoint: "mostweightRider",
    headers: ["NAME", "WEIGHT"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["weight", "rider_weight", "count", "total"],
    },
  },
  "riders-with-birthday": {
    apiEndpoint: "riderWithBirthday",
    headers: ["NAME", "TEAM", "BIRTHDAY"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["birthday", "birth_date", "count", "total"],
    },
  },
  "riders-birthday-today": {
    apiEndpoint: "ridersWithBirthdayToday",
    headers: ["NAME", "TEAM", "BIRTHDAY"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["birthday", "birth_date", "count", "total"],
    },
  },
  "team-most-nationalities": {
    apiEndpoint: "teamWithMostNationalities",
    headers: ["TEAM", "RESULT"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["team_country", "teamCountry", "country"],
      count: [
        "nationalities",
        "nationality_count",
        "count",
        "total",
        "win",
        "win_count",
      ],
    },
  },
  "team-most-riders": {
    apiEndpoint: "teamWithMostRider",
    headers: ["TEAM", "RIDERS"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["team_country", "teamCountry", "country"],
      count: ["riders", "rider_count", "count", "total"],
    },
  },
  // Race-related slugs
  "longest-races": {
    apiEndpoint: "longestRace",
    headers: ["RACE", "DISTANCE"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name", "race"],
      team: [],
      country: ["race_country", "country"],
      count: ["distance", "race_distance", "count", "total"],
    },
  },
  "shortest-races": {
    apiEndpoint: "shortestRace",
    headers: ["RACE", "DISTANCE"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name", "race"],
      team: ["race_type", "category"],
      country: ["race_country", "country", "country_code"],
      count: ["distance", "race_distance", "count", "total"],
    },
  },
  "most-riders-same-team": {
    apiEndpoint: "racesMOstRiderfromSameTeam",
    headers: ["RACE", "TEAM", "RIDERS"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["race_country", "country"],
      count: ["riders", "rider_count", "count", "total"],
    },
  },
  "best-country-ranking": {
    apiEndpoint: "bestCountryRanking",
    headers: ["COUNTRY", "RANKING"],
    dataPath: "data",
    itemConfig: {
      name: ["country_name", "countryName", "name"],
      team: ["country_code", "code"],
      country: ["country_code", "code"],
      count: ["ranking", "rank", "count", "total"],
    },
  },
  "recent-complete-race": {
    apiEndpoint: "recentCompleteRace",
    headers: ["RACE", "STATUS"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name"],
      team: ["race_type", "type", "category"],
      country: ["race_country", "country"],
      count: ["status", "race_status", "count", "total"],
    },
  },
  "finish-race": {
    apiEndpoint: "finishRace",
    headers: ["RACE", "STATUS"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name"],
      team: ["race_type", "type", "category"],
      country: ["race_country", "country"],
      count: ["status", "race_status", "count", "total"],
    },
  },
  "upcoming-races-last-year-riders": {
    apiEndpoint: "getUpcomingRacesByDate",
    headers: ["NAME", "TIME"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name"],
      team: ["race_type", "type", "category"],
      country: ["race_country", "country"],
      count: ["time", "race_time", "count", "total"],
    },
  },
  "most-win-upcoming-rider-last-year": {
    apiEndpoint: "getUpcomingRacesByDate",
    headers: ["NAME", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name"],
      team: ["race_type", "type", "category"],
      country: ["race_country", "country"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "tour-down-under-24": {
    apiEndpoint: "tourDownUnder24",
    headers: ["RACE", "DETAILS"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name"],
      team: ["race_type", "type", "category"],
      country: ["race_country", "country"],
      count: ["details", "race_details", "count", "total"],
    },
  },
  "most-win-tour-down-under": {
    apiEndpoint: "mostWinTourDownUnder",
    headers: ["NAME", "TEAM", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "tour-down-under-stage2": {
    apiEndpoint: "tourDownUnderStage2",
    headers: ["NAME", "TEAM", "RESULT"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["result", "stage_result", "count", "total"],
    },
  },
  // Team-related slugs
  "top3-stage-teams": {
    apiEndpoint: "top3StageTeam",
    headers: ["TEAM", "STAGE WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: [],
      country: ["team_country", "teamCountry", "country"],
      count: ["stage_wins", "stageWins", "count", "total"],
    },
  },
  "team-with-most-gc-wins": {
    apiEndpoint: "topGCRiderbyTeam",
    headers: ["TEAM", "COUNT"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: [],
      country: ["team_country", "teamCountry", "country"],
      count: ["gc_riders", "gcRiders", "count", "total"],
    },
  },
  "dnf-teams": {
    apiEndpoint: "DnfTeams",
    headers: ["TEAM", "DNFS"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: [],
      country: ["team_country", "teamCountry", "country", "flag"],
      count: ["dnfs", "dnf_count", "count", "total", "dnfCount"],
    },
  },
  "top-stage-riders-by-team": {
    apiEndpoint: "topStageRiderbyTeam",
    headers: ["TEAM", "STAGE RIDERS"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["team_country", "teamCountry", "country"],
      count: ["stage_riders", "stageRiders", "count", "total"],
    },
  },
  "top3-rank-one-teams": {
    apiEndpoint: "top3teamwithrank1",
    headers: ["TEAM", "RANK 1"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["team_country", "teamCountry", "country"],
      count: ["rank1_count", "rank1Count", "count", "total"],
    },
  },
  "top-gc-teams": {
    apiEndpoint: "top3GCTeam",
    headers: ["TEAM", "GC WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: [],
      country: ["team_country", "teamCountry", "country"],
      count: ["gc_wins", "gcWins", "count", "total"],
    },
  },
  "top10-gc-teams": {
    apiEndpoint: "top10GCTeams",
    headers: ["TEAM", "GC WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: [],
      country: ["team_country", "teamCountry", "country"],
      count: ["gc_wins", "gcWins", "count", "total"],
    },
  },
  "most-consistent-gc-teams": {
    apiEndpoint: "getMostConsistentGCTeams",
    headers: ["TEAM", "CONSISTENCY"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["team_country", "teamCountry", "country"],
      count: ["consistency", "consistency_score", "count", "total"],
    },
  },
  "top10-stage-teams": {
    apiEndpoint: "top10Stageteams",
    headers: ["TEAM", "STAGE WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["team_country", "teamCountry", "country"],
      count: ["stage_wins", "stageWins", "count", "total"],
    },
  },
  "most-podium-in-stages": {
    apiEndpoint: "mostPodiumInStages",
    headers: ["NAME", "TEAM", "PODIUM"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["podium", "podium_count", "count", "total"],
    },
  },
  "most-podium-in-gc": {
    apiEndpoint: "gcPodiums",
    headers: ["NAME", "TEAM", "PODIUM"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["podium", "podium_count", "count", "total"],
    },
  },
  "most-consistent-gc": {
    apiEndpoint: "mostConsistentGC",
    headers: ["NAME", "TEAM", "AVERAGE"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: [
        "avg_rank",
        "consistency",
        "consistency_score",
        "count",
        "total",
        "total_gc_races",

      ],
    },
  },
  "best-classics-riders": {
    apiEndpoint: "bestClassics",
    headers: ["NAME", "TEAM", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "top-gc-riders": {
    apiEndpoint: "gcTop10s",
    headers: ["NAME", "TEAM", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "team-with-most-consecutive-wins": {
    apiEndpoint: "top3teamwithrank1",
    headers: ["TEAM", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: [],
      country: ["team_country", "teamCountry", "country", "flag"],
      count: [
        "rank1_count",
        "rank1Count",
        "count",
        "total",
        "maxConsecutiveWins",
      ],
    },
  },
  "grand-tour-stage-wins": {
    apiEndpoint: "grandTourstageWin",
    headers: ["NAME", "TEAM", "STAGE WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["team_country", "teamCountry", "country", "rider_country"],
      count: ["stage_wins", "stageWins", "count", "total", "wins"],
    },
  },
  "top-gc-riders-last-year": {
    apiEndpoint: "getTopGC_RidersLastYear",
    headers: ["NAME", "TEAM", "TIME"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["time", "time_count", "count", "total"],
    },
  },
  "rider-most-stage-wins": {
    apiEndpoint: "getRiderWithMostStageWins",
    headers: ["NAME", "WINS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["stage_wins", "stageWins", "count", "total", "wins"],
    },
  },
  "most-gc-wins-in-race": {
    apiEndpoint: "getMostGCWinsInRace",
    headers: ["NAME", "TEAM", "WINS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["gc_wins", "gcWins", "count", "total", "wins"],
    },
  },
  "last-winner-stage": {
    apiEndpoint: "getLastWinner",
    headers: ["NAME", "TEAM", "YEAR"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["year", "win_year", "count", "total"],
    },
  },
  "rider-most-gc-top10s": {
    apiEndpoint: "getRiderWithMostGCTop10s",
    headers: ["NAME", "TEAM", "TOP 10S"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["top10s", "gc_top10s", "count", "total"],
    },
  },
  "rider-most-dnfs": {
    apiEndpoint: "getRiderWithMostDNFs",
    headers: ["NAME", "TEAM", "DNFS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["dnfs", "dnf_count", "count", "total"],
    },
  },
  "rider-most-gc-podiums": {
    apiEndpoint: "getRiderWithMostGCPodiums",
    headers: ["NAME", "TEAM", "PODIUMS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["podiums", "gc_podiums", "count", "total"],
    },
  },
  "rider-most-starts": {
    apiEndpoint: "getRiderWithMostStarts",
    headers: ["NAME", "TEAM", "STARTS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["starts", "start_count", "count", "total"],
    },
  },
  "last-race-winner-by-nationality": {
    apiEndpoint: "getLastRaceWinnerByNationality",
    headers: ["NAME", "YEAR"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["year", "win_year", "count", "total"],
    },
  },
  "most-stage-wins-by-nationality": {
    apiEndpoint: "getMostStageWinsByNationality",
    headers: ["NAME", "WINS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["stage_wins", "stageWins", "count", "total", "total_wins"],
    },
  },
  "most-participations-by-rider": {
    apiEndpoint: "getMostParticipationsByRider",
    headers: ["NAME", "PARTICIPATIONS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["participations", "participation_count", "count", "total"],
    },
  },
  "most-dnfs-by-nationality": {
    apiEndpoint: "getMostDNFsByNationality",
    headers: ["NAME", "DNFS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "rider.name"],
      team: ["team_name", "teamName", "team"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "rider.nationality",
      ],
      count: ["dnfs", "dnf_count", "count", "total", "totalDNFs"],
    },
  },
  "most-top10-race-by-nationality": {
    apiEndpoint: "getMostTop10RaceByNationality",
    headers: ["NAME", "TEAM", "TOP 10S"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["top10s", "top10_count", "count", "total"],
    },
  },
  "rider-podium-reach-by-nationality": {
    apiEndpoint: "getRiderPodiumReachByNationalty",
    headers: ["NAME", "PODIUMS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["podiums", "podium_count", "count", "total"],
    },
  },
  "youngest-participant-by-nationality": {
    apiEndpoint: "getYoungestParticipantByNationality",
    headers: ["NAME", "AGE"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "oldest-participant-by-nationality": {
    apiEndpoint: "getOldestParticipantByNationality",
    headers: ["NAME", "AGE"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "most-mountain-classification-wins": {
    apiEndpoint: "getMostMountainClassificationWins",
    headers: ["NAME", "WINS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["mountain_wins", "mountainWins", "count", "total"],
    },
  },
  "most-sprint-classification-wins": {
    apiEndpoint: "getMostSprintClassificationWins",
    headers: ["NAME", "WINS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["sprint_wins", "sprintWins", "count", "total"],
    },
  },
  "most-youngster-classification-wins": {
    apiEndpoint: "getMostYoungsterClassificationWins",
    headers: ["NAME", "WINS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: [
        "youngster_wins",
        "youngsterWins",
        "count",
        "total",
        "young_wins",
      ],
    },
  },
  "rider-with-most-finishes": {
    apiEndpoint: "getRiderWithMostFinishes",
    headers: ["NAME", "FINISHES"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["finishes", "finish_count", "count", "total"],
    },
  },
  "oldest-stage-winner": {
    apiEndpoint: "getOldestStageWinner",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "youngest-winner": {
    apiEndpoint: "getYoungestWinner",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "fastest-edition-of-race": {
    apiEndpoint: "getFastestEditionOfRace",
    headers: ["YEAR", "TIME"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["year", "edition_year", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["time", "time_taken", "count", "total", "total_time_formatted"],
    },
  },
  "longest-stage-in-race": {
    apiEndpoint: "getLongestStageInRace",
    headers: ["STAGE", "DISTANCE (KM)"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["stage", "stage_name", "name", "subtitle"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["distance", "distance_km", "count", "total"],
    },
  },
  "most-stage-departures": {
    apiEndpoint: "getMostStageDepartures",
    headers: ["NAME", "DEPARTURES"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "city"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["departures", "departure_count", "count", "total"],
    },
  },
  "team-with-most-wins": {
    apiEndpoint: "getTeamWithMostWins",
    headers: ["TEAM", "WINS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: [],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "nationality",
        "team_country",
      ],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "most-stage-finishes": {
    apiEndpoint: "getMostStageFinishes",
    headers: ["NAME", "FINISHES"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "city"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["finishes", "finish_count", "count", "total"],
    },
  },
  "youngest-top10-riders": {
    apiEndpoint: "getYoungestTop10Riders",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "shortest-stage-in-race": {
    apiEndpoint: "getShortestStageInRace",
    headers: ["STAGE", "DISTANCE (KM)"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["stage", "stage_name", "name", "subtitle"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["distance", "distance_km", "count", "total"],
    },
  },
  "oldest-top10-finisher": {
    apiEndpoint: "getOldestTop10Finisher",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "most-wins-in-race": {
    apiEndpoint: "mostWins",
    headers: ["NAME", "TEAM", "WINS"],
    dataPath: "data",
    idType: "raceDetailsStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "most-podiums-by-rider": {
    apiEndpoint: "getMostPodiumsByRiderInRace",
    headers: ["NAME", "PODIUMS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["podiums", "podium_count", "count", "total"],
    },
  },
  "race-participants": {
    apiEndpoint: "getRaceParticipants",
    headers: ["NAME", "COUNT"],
    dataPath: "data",
    idType: "raceDetailsStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["participations", "participation_count", "count", "total"],
    },
  },
  "team-with-most-wins-in-race": {
    apiEndpoint: "getTeamWithMostWinsInRace",
    headers: ["TEAM", "WINS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: [],
      country: ["team_country", "teamCountry", "country", "nationality"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "most-top10-by-rider": {
    apiEndpoint: "getMostTop10ByRiderInRace",
    headers: ["NAME", , "TOP 10 FINISHES"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["top10_finishes", "top10_count", "count", "total", "top_10s"],
    },
  },
  "last-winner": {
    apiEndpoint: "getLastWinner",
    headers: ["NAME", "YEAR"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["year", "winning_year", "count", "total"],
    },
  },
  "fastest-race-edition": {
    apiEndpoint: "getFastestRaceEdition",
    headers: ["WINNER", "YEAR", "TIME"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "winner"],
      team: ["team_name", "teamName", "year"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["time", "time_taken", "count", "total", "total_time_formatted"],
    },
  },
  "previous-editions": {
    apiEndpoint: "PreviousEditions",
    headers: ["WINNER", "YEAR", "TIME"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "winner"],
      team: ["team_name", "teamName", "year"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["time", "time_taken", "count", "total", "total_time_formatted"],
    },
  },
  "most-wins-nationality": {
    apiEndpoint: "getMostWinsNationality",
    headers: ["NATIONALITY", "TEAM", "WINS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["nationality", "country", "name", "rider_name"],
      team: ["team_name", "teamName", "team"],
      country: [
        "nationality",
        "country",
        "flag",
        "team_country",
        "rider_country",
      ],
      count: ["wins", "win_count", "count", "total", "total_wins"],
    },
  },
  "most-participations-by-rider": {
    apiEndpoint: "getMostParticipationsByRider",
    headers: ["NAME", "PARTICIPATIONS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["participations", "participation_count", "count", "total"],
    },
  },
  "most-dnfs-by-nationality-one-day-race": {
    apiEndpoint: "getMostDNFsByNationality",
    headers: ["NAME", "DNFS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["nationality", "country", "name", "rider_name", "rider.name"],
      team: ["team_name", "teamName", "team"],
      country: ["nationality", "country", "flag", "rider.nationality"],
      count: ["dnfs", "dnf_count", "count", "total", "totalDNFs"],
    },
  },
  "top5-spanish-results": {
    apiEndpoint: "getTop5SpanishResults",
    headers: ["NAME", "RANK"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "rider_name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["rank", "rank_count", "count", "total"],
    },
  },
  "last-race-winner-by-nationality": {
    apiEndpoint: "getLastRaceWinnerByNationality",
    headers: ["NATIONALITY", "YEAR"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["nationality", "country", "name", "rider_name"],
      team: [],
      country: ["nationality", "country", "flag", "rider_country"],
      count: ["year", "winning_year", "count", "total"],
    },
  },
  "top10-spanish-finishes": {
    apiEndpoint: "getTop10SpanishFinishes",
    headers: ["NAME", "TOP 10 FINISHES"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "rider_name"],
      team: ["team_name", "teamName", "team"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "nationality",
        "flag",
      ],
      count: ["top10_finishes", "top10_count", "count", "total"],
    },
  },
  "top-spanish-podium-reach": {
    apiEndpoint: "getTopSpainshPodiumReach",
    headers: ["NAME", "PODIUMS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "rider_name"],
      team: ["team_name", "teamName", "team"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "nationality",
        "flag",
      ],
      count: ["podiums", "podium_count", "count", "total"],
    },
  },
  "youngest-spanish-participant": {
    apiEndpoint: "getYoungestSpanishParticipant",
    headers: ["NAME", "AGE"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "rider_name"],
      team: ["team_name", "teamName", "team"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "nationality",
        "flag",
      ],
      count: ["age", "age_count", "count", "total", "date_of_birth"],
    },
  },
  "oldest-spanish-participant": {
    apiEndpoint: "getOldestSpanishParticipant",
    headers: ["NAME", "AGE"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "rider_name"],
      team: ["team_name", "teamName", "team"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "nationality",
        "flag",
      ],
      count: ["age", "age_count", "count", "total", "date_of_birth"],
    },
  },
  "rider-with-most-dnf": {
    apiEndpoint: "getRiderWithMostDNF",
    headers: ["NAME", "DNFS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["dnfs", "dnf_count", "count", "total"],
    },
  },
  "rider-with-most-finishes": {
    apiEndpoint: "getRiderWithMostFinishes",
    headers: ["NAME", "FINISHES"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["finishes", "finish_count", "count", "total"],
    },
  },
  "rider-with-most-consecutive-wins": {
    apiEndpoint: "getRiderWithMostConsecutiveWins",
    headers: ["NAME", "CONSECUTIVE WINS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: [
        "consecutive_wins",
        "consecutive_wins_count",
        "count",
        "total",
        "streak",
      ],
    },
  },
  "longest-race-edition": {
    apiEndpoint: "getLongestRaceEdition",
    headers: ["NAME", "YEAR", "DISTANCE (KM)"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["edition_year", "name", "subtitle"],
      team: ["team_name", "teamName", "team", "year"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "nationality",
        "nationality_filter",
      ],
      count: ["distance", "distance_km", "count", "total"],
    },
  },
  "edition-with-most-dnfs": {
    apiEndpoint: "getEditionWithMostDNFs",
    headers: ["NAME", "YEAR", "DNFS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["subtitle", "edition_year", "name"],
      team: ["team_name", "teamName", "team", "year"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["dnfs", "dnf_count", "count", "total"],
    },
  },
  "country-with-most-wins": {
    apiEndpoint: "getCountryWithMostWins",
    headers: ["COUNTRY", "WINS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["country", "nationality", "name", "most_wins_country"],
      team: ["team_name", "teamName", "team"],
      country: ["country", "nationality", "flag", "country_code"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "most-successful-team-in-race": {
    apiEndpoint: "getMostSuccessfulTeamInRace",
    headers: ["TEAM", "WINS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["team_name", "teamName", "name", "most_successful_team"],
      team: [],
      country: [
        "team_country",
        "teamCountry",
        "country",
        "nationality",
        "flag",
      ],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "oldest-top10-rider": {
    apiEndpoint: "getOldestTop10Rider",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "oldest_top10_rider"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "debut-riders-in-race": {
    apiEndpoint: "getDebutRidersInRace",
    headers: ["NAME", "TEAM", "DEBUT YEAR"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["debut_year", "debut_year_count", "count", "total", "year"],
    },
  },
  "winners-from-country": {
    apiEndpoint: "getWinnersFromCountry",
    headers: ["NAME", "YEAR", "TIME"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: [
        "rider_name",
        "riderName",
        "name",
        "winners_from_country",
        "winner_name",
      ],
      team: ["year", "winning_year", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["winning_year", "count", "total", "time"],
    },
  },
  "youngest-top10-rider": {
    apiEndpoint: "getYoungestTop10Rider",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "last-winner-from-country": {
    apiEndpoint: "getLastWinnerFromCountry",
    headers: ["NAME", "YEAR", "TIME"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: [
        "rider_name",
        "riderName",
        "name",
        "last_winner_from_country",
        "winner_name",
      ],
      team: ["year", "winning_year", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["time", "winning_year", "count", "total", "time"],
    },
  },

  "rider-last-victories": {
    apiEndpoint: "lastVictory",
    headers: ["RACE", "YEAR", "TIME"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race", "race_name", "raceName"],
      team: ["year", "rank", "team"],
      country: ["country", "nationality", "country_code"],
      count: ["time", "count", "rank"],
    },
  },



  "uci-points": {
    apiEndpoint: "uciPoints",
    headers: ["SEASON", "POINTS"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["season", "year", "name", "rider_name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["points", "uci_points", "count", "total", "total_uci_points"],
    },
  },
  "current-team": {
    apiEndpoint: "CurrentTeam",
    headers: ["TEAM", "YEAR", "YEARS"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: ["year", "season", "team"],
      country: [
        "team_country",
        "teamCountry",
        "country",
        "nationality",
        "flag",
      ],
      count: ["yearsInTeam", "season", "count", "total"],
    },
  },
  "wins-in-one-day": {
    apiEndpoint: "winsInOneDay",
    headers: ["RACE", "DATE", "RANK"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race_name", "raceName", "name"],
      team: ["race_date", "winning_year", "team"],
      country: ["race_country", "riderCountry", "country", "nationality"],
      count: ["rank", "rank_count", "count", "total"],
    },
  },
  "rider-years-active": {
    apiEndpoint: "getRiderYearsActive",
    headers: ["TEAM", "YEAR"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["team_name", "season", "name", "rider.name"],
      team: ["team_name", "teamName", "team"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "nationality",
        "rider.nationality",
        "flag",
      ],
      count: ["year", "season", "count", "total", "career_duration_years"],
    },
  },
  "rider-wins-by-season": {
    apiEndpoint: "getRiderWinsBySeason",
    headers: ["SEASON", "WINS"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["season", "year", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "time-since-last-victory": {
    apiEndpoint: "getTimeSinceLastVictory",
    headers: ["RACE", "DAYS"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race_name", "raceName", "race"],
      team: ["days", "time_since", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["days", "time_since", "count", "total", "days_since_last_win"],
    },
  },
  "rider-best-monument-results": {
    apiEndpoint: "getRiderBestMonumentResults",
    headers: ["RACE", "POSITION", "YEAR"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race_name", "raceName", "race"],
      team: ["position", "rank", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["year", "season", "count", "total"],
    },
  },

  "get-top10-stages-in-grand-tours": {
    apiEndpoint: "getTop10StagesInGrandTours",
    headers: ["RIDER", "YEAR", "COUNT"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["rider_name", "name", "riderName", "race"],
      team: ["year"],
      country: ["country", "nationality", "rider_country"],
      count: ["rank", "position", "count", "total"],
    },
  },

  "get-rider-first-win": {
    apiEndpoint: "getRiderFirstWin",
    headers: ["RIDER", "RACE", "YEAR"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["rider_name", "name", "riderName"],
      team: ["race_full_title", "race_name", "raceName"],
      country: ["country", "nationality", "rider_country"],
      count: ["year", "season", "count", "total"],
    },
  },

  "best-gc-results": {
    apiEndpoint: "bestGCResults",
    headers: ["RACE", "RANK"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["race", "name", "riderName"],
      team: [],
      country: ["country_code", "nationality", "rider_country"],
      count: ["rank", "position", "count", "total", "best_gc_rank"],
    },
  },

  "get-rider-longest-no-win-streak": {
    apiEndpoint: "getRiderLongestNoWinStreak",
    headers: ["RACE", "RANK", "YEAR"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race", "name", "riderName"],
      team: ["days", "days_without_win", "streak", "rank"],
      country: ["country", "nationality", "rider_country"],
      count: ["days", "count", "total", "days_without_win", "year"],
    },
  },

  "contact-history": {
    apiEndpoint: "contactHistory",
    headers: ["TEAM", "YEAR"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["rider_name", "name", "riderName", "contact_date"],
      team: ["team_name", "teamName", "team"],
      country: ["country", "nationality", "rider_country", "teamCountry"],
      count: ["contact_type", "type", "count", "total", "year"],
    },
  },

  "best-country": {
    apiEndpoint: "bestCountry",
    headers: ["COUNTRY", "WINS"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["country_name", "country", "best_country_name"],
      team: ["wins", "total_wins", "victories"],
      country: ["country", "nationality", "flag", "best_country_code"],
      count: ["total_wins", "wins", "count", "total", "winCount"],
    },
  },

  "home-country-wins": {
    apiEndpoint: "homeCountryWins",
    headers: ["RACE", "WINS"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race", "name", "riderName"],
      team: ["country", "home_country"],
      country: ["country", "nationality", "country_code"],
      count: ["wins", "total_wins", "count", "total", "race"],
    },
  },

  "rider-from-same-home-town": {
    apiEndpoint: "riderFromSameHomeTown",
    headers: ["RIDER", "BIRTH PLACE", "DOB"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["rider_name", "name", "riderName"],
      team: ["birth_place", "birth_date", "birth_year"],
      country: ["country", "nationality", "rider_country"],
      count: ["wins", "total_wins", "count", "total", "date_of_birth"],
    },
  },

  "get-rider-all-victories": {
    apiEndpoint: "getRiderAllVictories",
    headers: ["RACE", "YEAR", "RANK"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race", "name", "riderName"],
      team: ["race_name", "raceName", "year"],
      country: ["country", "nationality", "rider_country"],
      count: ["rank", "season", "count", "total"],
    },
  },
  "get-grand-tours-ridden": {
    apiEndpoint: "getGrandToursRidden",
    headers: ["GRAND TOUR", "RANK"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["grand_tour", "race", "race_name"],
      team: ["year", "position", "team"],
      country: ["country", "nationality", "country_code"],
      count: ["season", "count", "best_rank"],
    },
  },
  "rider-last-victory": {
    apiEndpoint: "getRiderLastVictorOneData",
    headers: ["RACE", "YEAR", "POSITION"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race", "race_name", "raceName"],
      team: ["year", "rank", "team"],
      country: ["country", "nationality", "country_code"],
      count: ["season", "count", "rank"],
    },
  },
  "get-rider-most-raced-country": {
    apiEndpoint: "getRiderMostRacedCountry",
    headers: ["COUNTRY", "RACES"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["country", "country_name", "nationality"],
      team: ["races", "race_count", "total_races"],
      country: ["wins", "win_count", "victories", "country_code"],
      count: ["year", "season", "count", "total_races", "races_count"],
    },
  },
  "get-best-stage-result": {
    apiEndpoint: "getBestStageResult",
    headers: ["RACE", "YEAR", "RANK"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["race_name", "race", "stageName"],
      team: ["year", "race_name", "raceName"],
      country: ["country", "nationality", "country_code"],
      count: ["rank", "season", "count"],
    },
  },
  "get-grand-tour-dnfs": {
    apiEndpoint: "getGrandTourDNFs",
    headers: ["GRAND TOUR", "YEAR"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["grand_tour", "race", "race_name"],
      team: [""],
      country: ["country", "nationality"],
      count: ["year"],
    },
  },
  "get-first-rank-in-grand-tours": {
    apiEndpoint: "getFirstRankInGrandTours",
    headers: ["GRAND TOUR", "YEAR"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["grand_tour", "race", "race_name"],
      team: ["rank", "position", "team"],
      country: ["country", "nationality", "country_code"],
      count: ["year", "season", "count"],
    },
  },
  "get-first-ever-grand-tour-win": {
    apiEndpoint: "getFirstEverGrandTourWin",
    headers: ["GRAND TOUR", "YEAR"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["grand_tour", "race", "race_name"],
      team: ["stage", "stage_name", "stageNumber"],
      country: ["country", "nationality", "country_code"],
      count: ["year", "season", "count"],
    },
  },
  "get-total-racing-days-in-grand-tours": {
    apiEndpoint: "getTotalRacingDaysInGrandTours",
    headers: ["GRAND TOUR", "DAYS", "YEAR"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["grand_tour", "race", "race_name"],
      team: ["days", "racing_days", "total_days"],
      country: ["country", "nationality", "country_code"],
      count: ["year", "season", "count"],
    },
  },
  "get-total-distance-raced-in-grand-tours": {
    apiEndpoint: "getTotalDistanceRacedInGrandTours",
    headers: ["GRAND TOUR", "DISTANCE", "YEAR"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["grand_tour", "race", "race_name"],
      team: ["distance_raced", "total_distance", "km"],
      country: ["country", "nationality", "country_code"],
      count: ["year", "season", "count"],
    },
  },
  "get-best-monument-results": {
    apiEndpoint: "getBestMonumentResults",
    headers: ["MONUMENT", "YEAR", "RANK"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["monument", "race", "race_name"],
      team: ["year", "position", "team"],
      country: ["country", "nationality", "country_code"],
      count: ["rank", "season", "count"],
    },
  },
  "get-best-paris-roubaix-result": {
    apiEndpoint: "getBestParisRoubaixResult",
    headers: ["RACE", "RANK", "TIME"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["race_name", "season", "race_year"],
      team: ["rank", "position", "team"],
      country: ["finish_time", "result", "country_code"],
      count: ["season", "count", "time"],
    },
  },
  "get-first-rank-in-monuments": {
    apiEndpoint: "getFirstRankInMonuments",
    headers: ["MONUMENT", "YEAR"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["monument", "race", "race_name"],
      team: ["rank", "position", "team"],
      country: ["country", "nationality", "country_code"],
      count: ["year", "season", "count"],
    },
  },
  "get-best-gc-result": {
    apiEndpoint: "getBestGCResult",
    headers: ["RACE", "YEAR", "RANK"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race", "race_name", "raceName"],
      team: ["year", "position", "team"],
      country: ["country", "nationality", "country_code"],
      count: ["season", "count", "gcRank"],
    },
  },
  "team-mates": {
    apiEndpoint: "teamMates",
    headers: ["TEAMMATE", "TEAM RACED"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["top_teammate", "rider_name", "name"],
      team: ["team", "team_name", "teamName"],
      country: ["country", "nationality"],
      count: ["times_raced", "season", "count"],
    },
  },
  "get-rider-last-place-finishes": {
    apiEndpoint: "getRiderLastPlaceFinishes",
    headers: ["RACE", "YEAR", "POSITION"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race", "race_name", "raceName"],
      team: ["year"],
      country: ["country", "nationality", "country_code"],
      count: ["position", "season", "rank"],
    },
  },
  "race-winners-by-nationality": {
    apiEndpoint: "getRaceWinnersByNationality",
    headers: ["RIDER", "TEAM", "TIME"],
    dataPath: "data",
    idType: "stages",
    itemConfig: {

      name: ["rider_name", "riderName", "name"],
      team: ["team_name"],
      country: ["rider_country", "flag", "riderCountry", "country"],
      count: ["time"],
    },
  },
  "oldest-rider-in-race": {
    apiEndpoint: "getOldestRiderInRace",
    headers: ["RIDER", "TEAM", "AGE"],
    dataPath: "data",
    idType: "stages",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["age", "rider_age", "count"],
    },
  },
  "youngest-rider-in-race": {
    apiEndpoint: "getYoungestRiderInRace",
    headers: ["RIDER", "TEAM", "AGE"],
    dataPath: "data",
    idType: "stages",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["age", "rider_age", "count"],
    },
  },
  "best-team-in-race": {
    apiEndpoint: "getBestTeamInRace",
    headers: ["TEAM", "RIDERS"],
    dataPath: "data",
    idType: "stages",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: ["performance_score", "score", "points"],
      country: ["team_country", "teamCountry", "country"],
      count: ["performance_score", "score", "count", "total", "rider_count"],
    },
  },
  "current-victory-ranking": {
    apiEndpoint: "getCurrentVictoryRanking",
    headers: ["RIDER", "TEAM", "VICTORIES"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["victories", "victory_count", "wins", "count", "total"],
    },
  },
  "current-team-ranking": {
    apiEndpoint: "getCurrentTeamRanking",
    headers: ["TEAM", "RANKING"],
    dataPath: "data",
    idType: "team",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: ["ranking", "rank", "position"],
      country: ["team_country", "teamCountry", "country"],
      count: ["ranking", "rank", "position", "count", "total_wins"],
    },
  },
  "best-riders-of-recent-year": {
    apiEndpoint: "getBestRidersOfRecentYear",
    headers: ["RIDER", "TEAM", "PERFORMANCE"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["performance_score", "score", "points", "count", "wins"],
    },
  },
  "oldest-riders": {
    apiEndpoint: "olderstRiders",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    idType: "riders",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["age", "rider_age", "count", "total"],
    },
  },
  "youngest-riders": {
    apiEndpoint: "youngestRiders",
    headers: ["RIDER", "TEAM", "AGE"],
    dataPath: "data",
    idType: "riders",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["age", "rider_age", "count", "total"],
    },
  },
  "victory-ranking": {
    apiEndpoint: "victoryRanking",
    headers: ["RIDER", "TEAM", "VICTORIES"],
    dataPath: "data",
    idType: "riders",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["victories", "victory_count", "wins", "count", "total"],
    },
  },
};
