export const SLUG_CONFIGS = {
  // Rider-related slugs
  "rider-results-this-year": {
    apiEndpoint: "getRiderWinsPodiumsTop10sCurrentYear",
    isList: false,                   
    headers: ["DATE", "RACE"," "],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name"],
      team: null,
      year: ["year"],
      wins_count: ["wins_count"],
      podium_count: ["podium_count"],
      top10_count: ["top10_count"],
       country: ["rider_country", "riderCountry", "country"],
     count: ["stage_wins", "stageWins", "count", "total","rank"],
   },
   },

  "top-10-in-stages": {
    apiEndpoint: "stageTop10sRider",
    headers: ["NAME", "TEAM", "COUNT"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team","teamSlug"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["stage_wins", "stageWins", "count", "total"],
    },
  },
  "rider-with-most-racing-days": {
    apiEndpoint: "mostRacingDays",
    headers: ["NAME", "TEAM", "RACING DAYS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team","teamSlug"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["racing_days", "racingDays", "count", "total"],
    },
  },
  "teams-with-most-wins": {
    apiEndpoint: "getTopStageRiders",
    headers: ["TEAM", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","riderSlug"],
      team: ["team_name", "teamName", "team","teamSlug"],
      country: ["rider_country", "riderCountry", "country", "flag"],
      count: ["wins", "stageWins", "count", "total"],
    },
  },
  "riders-with-birthday-today": {
    apiEndpoint: "ridersWithBirthdayToday",
    headers: ["NAME", "AGE"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","_id","riderSlug"],
      team: ["team_name", "teamName", "team","teamSlug"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "flag",
        "nationality",
      ],
      count: ["birthday", "birth_date", "count", "total", "age_today"],
    },
  },
  "team-with-most-rider-to-win-race": {
    apiEndpoint: "teamWithMostRider",
    headers: ["TEAM", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["race",],
      team: ["team_name", "teamName", "name","teamSlug"],
      country: ["team_country", "teamCountry", "country"],
      count: [
        "riders",
        "rider_count",
        "count",
        "total",
        "numberOfWinningRiders",
      ],
    },
  },
  "most-distance-raced": {
    apiEndpoint: "mostKMsRaced",
    headers: ["NAME", "TEAM", "KMS RACED"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "rider_key","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team", "team_name"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["kms_raced", "kmsRaced", "count", "total", "total_distance"],
    },
  },
  "most-races-won": {
    apiEndpoint: "mostWin",
    headers: ["NAME", "TEAM", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team","teamSlug"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "most-stage-wins": {
    apiEndpoint: "mostStageWins",
    headers: ["NAME", "TEAM", "STAGE WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["stage_wins", "stageWins", "count", "total"],
    },
  },
  "most-wins-overall-gc": {
    apiEndpoint: "mostGCWins",
    headers: ["NAME", "TEAM", "GC WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team","teamSlug"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["gc_wins", "gcWins", "count", "total"],
    },
  },
  "oldest-rider-in-races": {
    apiEndpoint: "oldestRider",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["age", "rider_age", "count", "total"],
    },
  },
  "youngest-riders-in-races": {
    apiEndpoint: "youngestRider",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["age", "rider_age", "count", "total"],
    },
  },
  "race-with-most-dnfs": {
    apiEndpoint: "mostDNFs",
    headers: ["RACE NAME", "DNFS"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["country_code", "country", "rider_country", "riderCountry"],
      count: ["dnfs", "dnf_count", "count", "total"],
    },
  },
  "most-mountain-wins": {
    apiEndpoint: "mostmountainwins",
    headers: ["NAME", "TEAM", "MOUNTAIN WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","_id","riderSlug"],
      team: ["team_name", "teamName", "team","teamSlug"],
      country: ["rider_country", "riderCountry", "country"],
      count: [
        "mountain_wins",
        "mountainWins",
        "count",
        "total",
        "totalKOMTitles",
      ],
    },
  },
  "most-sprint-wins": {
    apiEndpoint: "sprintWins",
    headers: ["NAME", "TEAM", "SPRINT WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["sprint_wins", "sprintWins", "count", "total"],
    },
  },
  "most-top5-no-wins": {
    apiEndpoint: "mostTop5Wins",
    headers: ["NAME", "TEAM", "TOP 5"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["top5_count", "top5Count", "count", "total"],
    },
  },
  "most-second-places": {
    apiEndpoint: "mostSecondPlaces",
    headers: ["NAME", "TEAM", "SECOND PLACES"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_key","riderSlug"],
      team: ["team_name", "teamName", "team","teamSlug"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["second_place_count", "secondPlaces", "count", "total"],
    },
  },
  "riders-yet-to-start": {
    apiEndpoint: "ridersYetToStart",
    headers: ["NAME", "TEAM", "STATUS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["status", "race_status", "count", "total"],
    },
  },
  "best-classics": {
    apiEndpoint: "bestClassics",
    headers: ["NAME", "TEAM", "CLASSIC WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["classic_wins", "classicWins", "count", "total"],
    },
  },
  "oldest-riders-with-most-wins": {
    apiEndpoint: "oldestMostWins",
    headers: ["NAME", "TEAM", "AGE", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["wins", "win_count", "count", "total"],
      age: ["age", "rider_age"],
    },
  },
  "youngest-riders-with-most-wins": {
    apiEndpoint: "youngestMostWins",
    headers: ["NAME", "TEAM", "AGE", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team","teamSlug"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["wins", "win_count", "count", "total"],
      age: ["age", "rider_age"],
    },
  },
  "oldest-active-riders": {
    apiEndpoint: "olderstRiders",
    headers: ["NAME","TEAM","AGE"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team","teamSlug"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["wins", "win_count", "count", "age"],
      // age: ["age", "rider_age"],
    },
  },
  "lightest-riders": {
    apiEndpoint: "lightestRider",
    headers: ["NAME", "WEIGHT"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","_id","riderSlug"],
      team: [""],
      country: ["rider_country", "riderCountry", "country"],
      count: ["weight", "rider_weight", "count", "total"],
    },
  },
  "heaviest-rider": {
    apiEndpoint: "mostweightRider",
    headers: ["NAME", "WEIGHT"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","_id","riderSlug"],
      team: [""],
      country: ["rider_country", "riderCountry", "country"],
      count: ["weight", "rider_weight", "count", "total"],
    },
  },
  "riders-with-birthday": {
    apiEndpoint: "riderWithBirthday",
    headers: ["NAME", "TEAM", "BIRTHDAY"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["birthday", "birth_date", "count", "total"],
    },
  },
  "riders-birthday-today": {
    apiEndpoint: "ridersWithBirthdayToday",
    headers: ["NAME", "TEAM", "BIRTHDAY"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["birthday", "birth_date", "count", "total"],
    },
  },
  "team-with-most-nationalities": {
    apiEndpoint: "teamWithMostNationalities",
    headers: ["TEAM", "RESULT"],
    dataPath: "data",
    itemConfig: {
      name: ["name"],
      team: ["team_name", "teamName", "team","teamSlug"],
      country: ["team_country", "teamCountry", "country"],
      count: [
        "nationalities",
        "nationality_count",
        "count",
        "total",
        "win",
        "win_count",
      ],
    },
  },
  "team-most-riders": {
    apiEndpoint: "teamWithMostRider",
    headers: ["TEAM", "RIDERS"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["team_country", "teamCountry", "country"],
      count: ["riders", "rider_count", "count", "total"],
    },
  },
  // Race-related slugs
  "longest-races": {
    apiEndpoint: "longestRace",
    headers: ["RACE", "DISTANCE"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name", "race"],
      team: [],
      country: ["race_country", "country"],
      count: ["distance", "race_distance", "count", "total"],
    },
  },
  "shortest-races": {
    apiEndpoint: "shortestRace",
    headers: ["RACE", "DISTANCE"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name", "race"],
      team: ["race_type", "category"],
      country: ["race_country", "country", "country_code"],
      count: ["distance", "race_distance", "count", "total"],
    },
  },
  "most-riders-same-team": {
    apiEndpoint: "racesMOstRiderfromSameTeam",
    headers: ["RACE", "TEAM", "RIDERS"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["race_country", "country"],
      count: ["riders", "rider_count", "count", "total"],
    },
  },
  "best-country-ranking": {
    apiEndpoint: "bestCountryRanking",
    headers: ["COUNTRY", "RANKING"],
    dataPath: "data",
    itemConfig: {
      name: ["country_name", "countryName", "name"],
      team: ["country_code", "code"],
      country: ["country_code", "code"],
      count: ["ranking", "rank", "count", "total"],
    },
  },
  "recent-complete-race": {
    apiEndpoint: "recentCompleteRace",
    headers: ["RACE", "STATUS"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name"],
      team: ["race_type", "type", "category"],
      country: ["race_country", "country"],
      count: ["status", "race_status", "count", "total"],
    },
  },
  "finish-race": {
    apiEndpoint: "finishRace",
    headers: ["RACE", "STATUS"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name"],
      team: ["race_type", "type", "category"],
      country: ["race_country", "country"],
      count: ["status", "race_status", "count", "total"],
    },
  },
  "upcoming-races-last-year-riders": {
    apiEndpoint: "getUpcomingRacesByDate",
    headers: ["NAME", "TIME"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name","rider_id","riderSlug"],
      team: ["race_type", "type", "category"],
      country: ["race_country", "country"],
      count: ["time", "race_time", "count", "total"],
    },
  },
  "most-win-upcoming-rider-last-year": {
    apiEndpoint: "getUpcomingRacesByDate",
    headers: ["NAME", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name","rider_id","riderSlug"],
      team: ["race_type", "type", "category"],
      country: ["race_country", "country"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "tour-down-under-24": {
    apiEndpoint: "tourDownUnder24",
    headers: ["RACE", "DETAILS"],
    dataPath: "data",
    itemConfig: {
      name: ["race_name", "raceName", "name"],
      team: ["race_type", "type", "category"],
      country: ["race_country", "country"],
      count: ["details", "race_details", "count", "total"],
    },
  },
  "most-win-tour-down-under": {
    apiEndpoint: "mostWinTourDownUnder",
    headers: ["NAME", "TEAM", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "tour-down-under-stage2": {
    apiEndpoint: "tourDownUnderStage2",
    headers: ["NAME", "TEAM", "RESULT"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["result", "stage_result", "count", "total"],
    },
  },
  // Team-related slugs
  "team-with-most-stage-podium-finishes": {
    apiEndpoint: "top3StageTeam",
    headers: ["TEAM", "STAGE WINS"],
    dataPath: "data",
    itemConfig: {
      name: [""],
      team: ["team_name", "teamName", "name"],
      country: ["team_country", "teamCountry", "country"],
      count: ["stage_wins", "stageWins", "count", "total"],
    },
  },
  "team-with-most-gc-wins": {
    apiEndpoint: "topGCRiderbyTeam",
    headers: ["TEAM", "COUNT"],
    dataPath: "data",
    itemConfig: {
      name: [""],
      team: ["team_name", "teamName", "name"],
      country: ["team_country", "teamCountry", "country"],
      count: ["gc_riders", "gcRiders", "count", "total"],
    },
  },
  "teams-with-most-dnf": {
    apiEndpoint: "DnfTeams",
    headers: ["TEAM", "DNFS"],
    dataPath: "data",
    itemConfig: {
      name: [""],
      team: ["team_name", "teamName", "name","team_id"],
      country: ["team_country", "teamCountry", "country", "flag"],
      count: ["dnfs", "dnf_count", "count", "total", "dnfCount"],
    },
  },
  "top-stage-riders-by-team": {
    apiEndpoint: "topStageRiderbyTeam",
    headers: ["TEAM", "STAGE RIDERS"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["team_country", "teamCountry", "country"],
      count: ["stage_riders", "stageRiders", "count", "total"],
    },
  },
  "top3-rank-one-teams": {
    apiEndpoint: "top3teamwithrank1",
    headers: ["TEAM", "RANK 1"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["team_country", "teamCountry", "country"],
      count: ["rank1_count", "rank1Count", "count", "total"],
    },
  },
  "teams-with-most-gc-podium-finishes": {
    apiEndpoint: "top3GCTeam",
    headers: ["TEAM", "GC WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: [],
      country: ["team_country", "teamCountry", "country"],
      count: ["gc_wins", "gcWins", "count", "total"],
    },
  },
  "teams-with-most-top-10-gc-finishes": {
    apiEndpoint: "top10GCTeams",
    headers: ["TEAM", "GC WINS"],
    dataPath: "data",
    itemConfig: {
      name: [""],
      team: ["team_name", "teamName", "name"],
      country: ["team_country", "teamCountry", "country"],
      count: ["gc_wins", "gcWins", "count", "total"],
    },
  },
  "most-consistent-gc-teams": {
    apiEndpoint: "getMostConsistentGCTeams",
    headers: ["TEAM", "CONSISTENCY"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["team_country", "teamCountry", "country"],
      count: ["consistency", "consistency_score", "count", "total"],
    },
  },
  "top10-stage-teams": {
    apiEndpoint: "top10Stageteams",
    headers: ["TEAM", "STAGE WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["team_country", "teamCountry", "country"],
      count: ["stage_wins", "stageWins", "count", "total"],
    },
  },
  "most-podium-in-stage": {
    apiEndpoint: "mostPodiumInStages",
    headers: ["NAME", "TEAM", "PODIUM",],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["podium", "podium_count", "count", "total"],
    },
  },
  "most-podiums-in-gc": {
    apiEndpoint: "gcPodiums",
    headers: ["NAME", "TEAM", "PODIUM"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["podium", "podium_count", "count", "total"],
    },
  },
  "most-consistent-gc": {
    apiEndpoint: "mostConsistentGC",
    headers: ["NAME", "TEAM", "AVERAGE"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: [
        "avg_rank",
        "consistency",
        "consistency_score",
        "count",
        "total",
        "total_gc_races",

      ],
    },
  },
  "best-classics-rider": {
    apiEndpoint: "bestClassics",
    headers: ["NAME", "TEAM", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "top-10-in-gc": {
    apiEndpoint: "gcTop10s",
    headers: ["NAME", "TEAM", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "team-with-most-consecutive-wins": {
    apiEndpoint: "top3teamwithrank1",
    headers: ["TEAM", "WINS"],
    dataPath: "data",
    itemConfig: {
      name: [""],
      team: ["team_name", "teamName", "name"],
      country: ["team_country", "teamCountry", "country", "flag"],
      count: [
        "rank1_count",
        "rank1Count",
        "count",
        "total",
        "maxConsecutiveWins",
      ],
    },
  },
  "grand-tour-stage-winners": {
    apiEndpoint: "grandTourstageWin",
    headers: ["NAME", "TEAM", "STAGE WINS"],
    dataPath: "data",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["team_country", "teamCountry", "country", "rider_country"],
      count: ["stage_wins", "stageWins", "count", "total", "wins"],
    },
  },
  "top-last-year-gc": {
    apiEndpoint: "getTopGC_RidersLastYear",
    headers: ["NAME", "TEAM", "TIME"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["time", "time_count", "count", "total"],
    },
  },
  "rider-most-stage-wins": {
    apiEndpoint: "getRiderWithMostStageWins",
    headers: ["NAME", "WINS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["stage_wins", "stageWins", "count", "total", "wins"],
    },
  },
  "most-wins-gc": {
    apiEndpoint: "getMostGCWinsInRace",
    headers: ["NAME", "TEAM", "WINS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["gc_wins", "gcWins", "count", "total", "wins"],
    },
  },
  "last-winners": {
    apiEndpoint: "getLastWinner",
    headers: ["NAME", "TEAM", "YEAR"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["year", "win_year", "count", "total"],
    },
  },
  "rider-with-most-top10-gc": {
    apiEndpoint: "getRiderWithMostGCTop10s",
    headers: ["NAME", "TEAM", "TOP 10S"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["top10s", "gc_top10s", "count", "total"],
    },
  },
  "rider-with-most-dnfs": {
    apiEndpoint: "getRiderWithMostDNFs",
    headers: ["NAME", "TEAM", "DNFS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["dnfs", "dnf_count", "count", "total"],
    },
  },
  "rider-with-most-gc-podiums": {
    apiEndpoint: "getRiderWithMostGCPodiums",
    headers: ["NAME", "TEAM", "PODIUMS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["podiums", "gc_podiums", "count", "total"],
    },
  },
  "rider-with-most-starts": {
    apiEndpoint: "getRiderWithMostStarts",
    headers: ["NAME", "TEAM", "STARTS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["starts", "start_count", "count", "total"],
    },
  },
  "last-time-rider-won": {
    apiEndpoint: "getLastRaceWinnerByNationality",
    headers: ["NAME", "YEAR"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["year", "win_year", "count", "total"],
    },
  },
  "most-stage-wins-by-nationality": {
    apiEndpoint: "getMostStageWinsByNationality",
    headers: ["NAME", "WINS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["stage_wins", "stageWins", "count", "total", "total_wins"],
    },
  },
  "most-participations-by-riders": {
    apiEndpoint: "getMostParticipationsByRider",
    headers: ["NAME", "PARTICIPATIONS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["participations", "participation_count", "count", "total"],
    },
  },
  "rider-with-most-dnf-by-nationality": {
    apiEndpoint: "getMostDNFsByNationality",
    headers: ["NAME", "DNFS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "rider.nationality",
        "nationality"
      ],
      count: ["dnfs", "dnf_count", "count", "total", "totalDNFs"],
    },
  },
  "most-top10-final-gc-by-nationality": {
    apiEndpoint: "getMostTop10RaceByNationality",
    headers: ["NAME", "TEAM", "TOP 10S"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["top10s", "top10_count", "count", "total"],
    },
  },
  "riders-to-reach-the-podium": {
    apiEndpoint: "getRiderPodiumReachByNationalty",
    headers: ["NAME", "PODIUMS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["podiums", "podium_count", "count", "total"],
    },
  },
  "youngest-participant-by-nationality": {
    apiEndpoint: "getYoungestParticipantByNationality",
    headers: ["NAME", "AGE"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "oldest-participant-by-nationality": {
    apiEndpoint: "getOldestParticipantByNationality",
    headers: ["NAME", "AGE"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "most-wins-in-mountain-classification": {
    apiEndpoint: "getMostMountainClassificationWins",
    headers: ["NAME", "WINS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["mountain_wins", "mountainWins", "count", "total"],
    },
  },
  "most-wins-in-sprint-classification": {
    apiEndpoint: "getMostSprintClassificationWins",
    headers: ["NAME", "WINS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["sprint_wins", "sprintWins", "count", "total"],
    },
  },
  "most-wins-in-youngster-classification": {
    apiEndpoint: "getMostYoungsterClassificationWins",
    headers: ["NAME", "WINS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: [
        "youngster_wins",
        "youngsterWins",
        "count",
        "total",
        "young_wins",
      ],
    },
  },
  "rider-with-most-finish": {
    apiEndpoint: "getRiderWithMostFinishes",
    headers: ["NAME", "FINISHES"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["finishes", "finish_count", "count", "total"],
    },
  },
  "oldest-stage-winners": {
    apiEndpoint: "getOldestStageWinner",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "youngest-stage-winners": {
    apiEndpoint: "getYoungestWinner",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "fastest-editions": {
    apiEndpoint: "getFastestEditionOfRace",
    headers: ["YEAR", "TIME"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["year", "edition_year", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["time", "time_taken", "count", "total", "total_time_formatted"],
    },
  },
  "longest-stage-in-race": {
    apiEndpoint: "getLongestStageInRace",
    headers: ["STAGE", "DISTANCE (KM)"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["stage", "stage_name", "name", "subtitle","race_name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["distance", "distance_km", "count", "total"],
    },
  },
  "cities-with-most-departures": {
    apiEndpoint: "getMostStageDepartures",
    headers: ["NAME", "DEPARTURES"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "city"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["departures", "departure_count", "count", "total"],
    },
  },
  "team-with-most-wins": {
    apiEndpoint: "getTeamWithMostWins",
    headers: ["TEAM", "WINS"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: [""],
      team: ["team_name", "teamName", "name"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "nationality",
        "team_country",
      ],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "cities-with-most-often-used-as-finish": {
    apiEndpoint: "getMostStageFinishes",
    headers: ["NAME", "FINISHES"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "city"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["finishes", "finish_count", "count", "total"],
    },
  },
  "youngest-top10-riders": {
    apiEndpoint: "getYoungestTop10Riders",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "shortest-stage-in-race": {
    apiEndpoint: "getShortestStageInRace",
    headers: ["STAGE", "DISTANCE (KM)"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["stage", "stage_name", "name", "subtitle","race_name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["distance", "distance_km", "count", "total"],
    },
  },
  "oldest-top10-finisher": {
    apiEndpoint: "getOldestTop10Finisher",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    idType: "stageStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "most-win": {
    apiEndpoint: "mostWins",
    headers: ["NAME", "TEAM", "WINS"],
    dataPath: "data",
    idType: "raceDetailsStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "most-podiums-spots": {
    apiEndpoint: "getMostPodiumsByRiderInRace",
    headers: ["NAME", "PODIUMS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["podiums", "podium_count", "count", "total"],
    },
  },
  "race-participants": {
    apiEndpoint: "getRaceParticipants",
    headers: ["NAME", "COUNT"],
    dataPath: "data",
    idType: "raceDetailsStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["participations", "participation_count", "count", "total"],
    },
  },
  "team-with-most-win": {
    apiEndpoint: "getTeamWithMostWinsInRace",
    headers: ["TEAM", "WINS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: [""],
      team: ["team_name", "teamName", "name"],
      country: ["team_country", "teamCountry", "country", "nationality"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "most-times-top10": {
    apiEndpoint: "getMostTop10ByRiderInRace",
    headers: ["NAME", , "TOP 10 FINISHES"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["top10_finishes", "top10_count", "count", "total", "top_10s"],
    },
  },
  "last-winner": {
    apiEndpoint: "getLastWinner",
    headers: ["NAME", "YEAR"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["year", "winning_year", "count", "total"],
    },
  },
  "fastest-race-edition": {
    apiEndpoint: "getFastestRaceEdition",
    headers: ["WINNER", "YEAR", "TIME"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "winner","rider_id","riderSlug"],
      team: ["team_name", "teamName", "year"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["time", "time_taken", "count", "total", "total_time_formatted"],
    },
  },
  "previous-editions": {
    apiEndpoint: "PreviousEditions",
    headers: ["WINNER", "YEAR", "TIME"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "winner","winner_id","riderSlug"],
      team: ["team_name", "teamName", "year"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["time", "time_taken", "count", "total", "total_time_formatted"],
    },
  },
  "most-wins-nationality": {
    apiEndpoint: "getMostWinsNationality",
    headers: ["NATIONALITY", "TEAM", "WINS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["nationality", "country", "name", "rider_name","_id"],
      team: ["team_name", "teamName", "team"],
      country: [
        "nationality",
        "country",
        "flag",
        "team_country",
        "rider_country",
      ],
      count: ["wins", "win_count", "count", "total", "total_wins"],
    },
  },
  "most-participations-by-rider": {
    apiEndpoint: "getMostParticipationsByRider",
    headers: ["NAME", "PARTICIPATIONS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["participations", "participation_count", "count", "total"],
    },
  },
  "most-dnfs-by-nationality-one-day-race": {
    apiEndpoint: "getMostDNFsByNationality",
    headers: ["NAME", "DNFS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["country", "name", "rider_name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["nationality", "country", "flag", "rider.nationality"],
      count: ["dnfs", "dnf_count", "count", "total", "totalDNFs"],
    },
  },
  "top-best-results": {
    apiEndpoint: "getTop5SpanishResults",
    headers: ["NAME", "RANK"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "rider_name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["rank", "rank_count", "count", "total"],
    },
  },
  "last-time-rider-won-by-nationality": {
    apiEndpoint: "getLastRaceWinnerByNationality",
    headers: ["NATIONALITY", "YEAR"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["nationality", "country", "name", "rider_name","rider_id","riderSlug"],
      team: [],
      country: ["nationality", "country", "flag", "rider_country"],
      count: ["year", "winning_year", "count", "total"],
    },
  },
  "riders-with-most-top10": {
    apiEndpoint: "getTop10SpanishFinishes",
    headers: ["NAME", "TOP 10 FINISHES"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "rider_name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "nationality",
        "flag",
      ],
      count: ["top10_finishes", "top10_count", "count", "total"],
    },
  },
  "rider-with-most-podium-finishes": {
    apiEndpoint: "getTopSpainshPodiumReach",
    headers: ["NAME", "PODIUMS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "rider_name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "nationality",
        "flag",
      ],
      count: ["podiums", "podium_count", "count", "total"],
    },
  },
  "youngest-rider-to-participate": {
    apiEndpoint: "getYoungestSpanishParticipant",
    headers: ["NAME", "AGE"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "rider_name" ,"rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "nationality",
        "flag",
      ],
      count: ["age", "age_count", "count", "total", "date_of_birth"],
    },
  },
  "oldest-rider-to-participate": {
    apiEndpoint: "getOldestSpanishParticipant",
    headers: ["NAME", "AGE"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "rider_name" ,"rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "nationality",
        "flag",
      ],
      count: ["age", "age_count", "count", "total", "date_of_birth"],
    },
  },
  "rider-with-most-dnf": {
    apiEndpoint: "getRiderWithMostDNF",
    headers: ["NAME", "DNFS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["dnfs", "dnf_count", "count", "total"],
    },
  },
  "rider-with-most-finishes": {
    apiEndpoint: "getRiderWithMostFinishes",
    headers: ["NAME", "FINISHES"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name"  ,"rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["finishes", "finish_count", "count", "total"],
    },
  },
  "rider-with-most-consecutive-wins": {
    apiEndpoint: "getRiderWithMostConsecutiveWins",
    headers: ["NAME", "CONSECUTIVE WINS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: [
        "consecutive_wins",
        "consecutive_wins_count",
        "count",
        "total",
        "streak",
      ],
    },
  },
  "longest-race-edition": {
    apiEndpoint: "getLongestRaceEdition",
    headers: ["NAME", "YEAR", "DISTANCE (KM)"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["edition_year", "name", "subtitle","race_name"],
      team: ["team_name", "teamName", "team", "year"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "nationality",
        "nationality_filter",
      ],
      count: ["distance", "distance_km", "count", "total"],
    },
  },
  "edition-with-most-dnfs": {
    apiEndpoint: "getEditionWithMostDNFs",
    headers: ["NAME", "YEAR", "DNFS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["subtitle", "edition_year", "name" ,"race_name"],
      team: ["team_name", "teamName", "team", "year"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["dnfs", "dnf_count", "count", "total"],
    },
  },
  "country-with-most-wins": {
    apiEndpoint: "getCountryWithMostWins",
    headers: ["COUNTRY", "WINS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["country", "nationality", "name", "most_wins_country"],
      team: ["team_name", "teamName", "team"],
      country: ["country", "nationality", "flag", "country_code"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "most-successful-team-in-race": {
    apiEndpoint: "getMostSuccessfulTeamInRace",
    headers: ["TEAM", "WINS"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: [""],
      team: ["team_name", "teamName", "name", "most_successful_team"],
      country: [
        "team_country",
        "teamCountry",
        "country",
        "nationality",
        "flag",
      ],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "oldest-top10-rider": {
    apiEndpoint: "getOldestTop10Rider",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name", "oldest_top10_rider","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "debut-riders-in-race": {
    apiEndpoint: "getDebutRidersInRace",
    headers: ["NAME", "TEAM", "DEBUT YEAR"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["debut_year", "debut_year_count", "count", "total", "year"],
    },
  },
  "winners-from-country": {
    apiEndpoint: "getWinnersFromCountry",
    headers: ["NAME", "YEAR", "TIME"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: [
        "rider_name",
        "riderName",
        "name",
        "winners_from_country",
        "winner_name",
        "winner_id",
        "riderSlug",
      ],
      team: ["year", "winning_year", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["winning_year", "count", "total", "time"],
    },
  },
  "youngest-top10-rider": {
    apiEndpoint: "getYoungestTop10Rider",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["age", "age_count", "count", "total"],
    },
  },
  "last-winner-from-country": {
    apiEndpoint: "getLastWinnerFromCountry",
    headers: ["NAME", "YEAR", "TIME"],
    dataPath: "data",
    idType: "oneDayRaceStats",
    itemConfig: {
      name: [
        "rider_name",
        "riderName",
        "name",
        "last_winner_from_country",
        "winner_name",
        "winner_id",
        "riderSlug",
      ],
      team: ["year", "winning_year", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["time", "winning_year", "count", "total", "time"],
    },
  },

  "rider-last-victories": {
    apiEndpoint: "lastVictory",
    headers: ["RACE", "YEAR", "TIME"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race", "race_name", "raceName"],
      team: ["year", "rank", "team"],
      country: ["country", "nationality", "country_code"],
      count: ["time", "count", "rank"],
    },
  },



  "current-uci-ranking": {
    apiEndpoint: "uciPoints",
    headers: ["RIDER", "POINTS"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["season", "year", "name", "rider_name", "rider_id", "riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["points", "uci_points", "count", "total", "total_uci_points"],
    },
  },
  "current-team": {
    apiEndpoint: "CurrentTeam",
    headers: ["TEAM", "YEAR", "YEARS"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["team_name", "teamName", "name"],
      team: ["year", "season", "team"],
      country: [
        "team_country",
        "teamCountry",
        "country",
        "nationality",
        "flag",
      ],
      count: ["yearsInTeam", "season", "count", "total"],
    },
  },
  "wins-in-one-day-races": {
    apiEndpoint: "winsInOneDay",
    headers: ["RACE","RANK"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race_name", "raceName", "name"],
      team: [ "winning_year", "team"],
      country: ["race_country", "riderCountry", "country", "nationality"],
      count: ["rank", "rank_count", "count", "total"],
    },
  },
  "professional since": {
    apiEndpoint: "getRiderYearsActive",
    headers: ["TEAM", "YEAR"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["team_name", "season", "name", "rider.name"],
      team: ["team_name", "teamName", "team"],
      country: [
        "rider_country",
        "riderCountry",
        "country",
        "nationality",
        "rider.nationality",
        "flag",
      ],
      count: ["year", "season", "count", "total", "career_duration_years"],
    },
  },
  "number-of-wins-per-season": {
    apiEndpoint: "getRiderWinsBySeason",
    headers: ["SEASON", "WINS"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["season", "year", "name"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["wins", "win_count", "count", "total"],
    },
  },
  "time-since-last-win": {
    apiEndpoint: "getTimeSinceLastVictory",
    headers: ["RACE", "DAYS"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race_name", "raceName", "race"],
      team: ["days", "time_since", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["days", "time_since", "count", "total", "days_since_last_win"],
    },
  },
  "best-monuments-result": {
    apiEndpoint: "getRiderBestMonumentResults",
    headers: ["RACE", "POSITION", "YEAR"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race_name", "raceName", "race"],
      team: ["position", "rank", "team"],
      country: ["rider_country", "riderCountry", "country", "nationality"],
      count: ["year", "season", "count", "total"],
    },
  },

  "top-finishes-in-grand-tour-satges": {
    apiEndpoint: "getTop10StagesInGrandTours",
    headers: ["RACE","COUNT"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["rider_name", "name", "riderName", "race"],
      team: [""],
      country: ["country", "nationality", "rider_country"],
      count: ["rank", "position", "count", "total"],
    },
  },

  "rider-first-win": {
    apiEndpoint: "getRiderFirstWin",
    headers: ["RIDER", "RACE", "YEAR"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["rider_name", "name", "riderName","rider_id","riderSlug"],
      team: ["race_full_title", "race_name", "raceName"],
      country: ["country", "nationality", "rider_country"],
      count: ["year", "season", "count", "total"],
    },
  },

  "grand-tour-gc-wins": {
    apiEndpoint: "bestGCResults",
    headers: ["RACE", "RANK"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["race", "name", "riderName"],
      team: [],
      country: ["country_code", "nationality", "rider_country"],
      count: ["rank", "position", "count", "total", "best_gc_rank"],
    },
  },

  "rider-longest-streak-without-win": {
    apiEndpoint: "getRiderLongestNoWinStreak",
    headers: ["RACE", "RANK", "YEAR"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race", "name", "riderName"],
      team: ["days", "days_without_win", "streak", "rank"],
      country: ["country_code", "nationality", "rider_country"],
      count: ["days", "count", "total", "days_without_win", "year"],
    },
  },

  "team-contract-history": {
    apiEndpoint: "contactHistory",
    headers: ["TEAM", "YEAR"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["rider_name", "name", "riderName", "contact_date"],
      team: ["team_name", "teamName", "team"],
      country: ["country", "nationality", "rider_country", "teamCountry"],
      count: ["contact_type", "type", "count", "total", "year"],
    },
  },

  "best-performance-in-country": {
    apiEndpoint: "bestCountry",
    headers: ["COUNTRY", "WINS"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["country_name", "country", "best_country_name"],
      team: ["wins", "total_wins", "victories"],
      country: ["country", "nationality", "flag", "best_country_code"],
      count: ["total_wins", "wins", "count", "total", "winCount"],
    },
  },

  "home-country-wins": {
    apiEndpoint: "homeCountryWins",
    headers: ["RACE", "WINS"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race", "name", "riderName"],
      team: ["country", "home_country"],
      country: ["country", "nationality", "country_code"],
      count: ["wins", "total_wins", "count", "total", "race"],
    },
  },

  "riders-with-same-birthplace": {
    apiEndpoint: "riderFromSameHomeTown",
    headers: ["RIDER", "BIRTH PLACE", "DOB"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["rider_name", "name", "riderName","_id","riderSlug"],
      team: ["birth_place", "birth_date", "birth_year"],
      country: ["nationality"],
      count: ["date_of_birth"],
    },
  },

  "riders-victories": {
    apiEndpoint: "getRiderAllVictories",
    headers: ["RACE", "YEAR", "RANK"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race", "name", "riderName"],
      team: ["race_name", "raceName", "year"],
      country: ["country", "nationality", "rider_country"],
      count: ["rank", "season", "count", "total"],
    },
  },
  "grand-tours-ridden": {
    apiEndpoint: "getGrandToursRidden",
    headers: ["RACE", "RANK"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["grand_tour", "race", "race_name"],
      team: ["year", "position", "team"],
      country: ["country", "nationality", "country_code"],
      count: ["season", "count", "best_rank"],
    },
  },
  "rider-last-victory": {
    apiEndpoint: "getRiderLastVictorOneData",
    headers: ["RACE", "YEAR", "POSITION"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race", "race_name", "raceName"],
      team: ["year", "rank", "team"],
      country: ["country", "nationality", "country_code"],
      count: ["season", "count", "rank"],
    },
  },
  "rider-most-raced-countries": {
    apiEndpoint: "getRiderMostRacedCountry",
    headers: ["COUNTRY", "RACES"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["country", "country_name", "nationality"],
      team: ["races", "race_count", "total_races"],
      country: ["wins", "win_count", "victories", "country_code"],
      count: ["year", "season", "count", "total_races", "races_count"],
    },
  },
  "best-stage-results": {
    apiEndpoint: "getBestStageResult",
    headers: ["RACE", "YEAR", "RANK"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["race_name", "race", "stageName"],
      team: ["year", "race_name", "raceName"],
      country: ["country", "nationality", "country_code"],
      count: ["rank", "season", "count"],
    },
  },
  "grand-tour-dnfs": {
    apiEndpoint: "getGrandTourDNFs",
    headers: ["GRAND TOUR", "YEAR"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["grand_tour", "race", "race_name"],
      team: [""],
      country: ["country", "nationality"],
      count: ["year"],
    },
  },
  "victory-in-grand-tours": {
    apiEndpoint: "getFirstRankInGrandTours",
    headers: ["GRAND TOUR", "YEAR"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["grand_tour", "race", "race_name"],
      team: ["rank", "position", "team"],
      country: ["country", "nationality", "country_code"],
      count: ["year", "season", "count"],
    },
  },
  "first-grand-tour-win": {
    apiEndpoint: "getFirstEverGrandTourWin",
    headers: ["GRAND TOUR", "YEAR"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["grand_tour", "race", "race_name"],
      team: ["stage", "stage_name", "stageNumber"],
      country: ["country", "nationality", "country_code"],
      count: ["year", "season", "count"],
    },
  },
  "total-grand-tour-racing-days": {
    apiEndpoint: "getTotalRacingDaysInGrandTours",
    headers: ["RACE", "DAYS", "YEAR"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["grand_tour", "race", "race_name"],
      team: ["days", "racing_days", "total_days"],
      country: ["country", "nationality", "country_code"],
      count: ["year", "season", "count"],
    },
  },
  "total-distance-grand-tour": {
    apiEndpoint: "getTotalDistanceRacedInGrandTours",
    headers: ["RACE", "DISTANCE", "YEAR"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["grand_tour", "race", "race_name"],
      team: ["distance_raced", "total_distance", "km"],
      country: ["country", "nationality", "country_code"],
      count: ["year", "season", "count"],
    },
  },
  "riders-best-monuments-results": {
    apiEndpoint: "getBestMonumentResults",
    headers: ["RACE", "YEAR", "RANK"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["monument", "race", "race_name"],
      team: ["year", "position", "team"],
      country: ["country", "nationality", "country_code"],
      count: ["rank", "season", "count"],
    },
  },
  "riders-paris-roubaix-results": {
    apiEndpoint: "getBestParisRoubaixResult",
    headers: ["RACE", "RANK", "TIME"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["race_name", "season", "race_year"],
      team: ["rank", "position", "team"],
      country: ["finish_time", "result", "country_code"],
      count: ["season", "count", "time"],
    },
  },
  "victory-in-monuments": {
    apiEndpoint: "getFirstRankInMonuments",
    headers: ["RACE", "YEAR"],
    dataPath: "data",
    idType: "race",
    itemConfig: {
      name: ["monument", "race", "race_name"],
      team: ["rank", "position", "team"],
      country: ["country", "nationality", "country_code"],
      count: ["year", "season", "count"],
    },
  },
  "best-gc-result-in-grand-tour": {
    apiEndpoint: "getBestGCResult",
    headers: ["RACE", "YEAR", "RANK"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race", "race_name", "raceName"],
      team: ["year", "position", "team"],
      country: ["country", "nationality", "country_code"],
      count: ["season", "count", "gcRank"],
    },
  },
  "most-frequent-teammate": {
    apiEndpoint: "teamMates",
    headers: ["RIDER", "NUMBER OF RACES"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["top_teammate", "rider_name", "name","rider_id"],
      team: ["team", "team_name", "teamName"],
      country: ["country", "nationality"],
      count: ["times_raced", "season", "count"],
    },
  },
  "rider-last-place-finishes": {
    apiEndpoint: "getRiderLastPlaceFinishes",
    headers: ["RACE", "YEAR", "POSITION"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["race", "race_name", "raceName"],
      team: ["year"],
      country: ["country", "nationality", "country_code"],
      count: ["position", "season", "rank"],
    },
  },
  "winning-nationality-for-this-race": {
    apiEndpoint: "getRaceWinnersByNationality",
    headers: ["RIDER", "TEAM", "TIME"],
    dataPath: "data",
    idType: "stages",
    itemConfig: {

      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name"],
      country: ["rider_country", "flag", "riderCountry", "country"],
      count: ["time"],
    },
  },
  "oldest-riders-in-race": {
    apiEndpoint: "getOldestRiderInRace",
    headers: ["RIDER", "TEAM", "AGE"],
    dataPath: "data",
    idType: "stages",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["age", "rider_age", "count"],
    },
  },
  "youngest-riders-in-race": {
    apiEndpoint: "getYoungestRiderInRace",
    headers: ["RIDER", "TEAM", "AGE"],
    dataPath: "data",
    idType: "stages",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["age", "rider_age", "count"],
    },
  },
  "best-teams-in-the-race": {
    apiEndpoint: "getBestTeamInRace",
    headers: ["TEAM",""],
    dataPath: "data",
    idType: "stages",
    itemConfig: {
      name: [""],
      team: ["team_name", "teamName", "name",],
      country: ["team_country", "teamCountry", "country"],
      count: [""],
    },
  },
  "recent-victory-ranking": {
    apiEndpoint: "getCurrentVictoryRanking",
    headers: ["RIDER", "TEAM", "VICTORIES"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["victories", "victory_count", "wins", "count", "total"],
    },
  },
  "recent-team-ranking": {
    apiEndpoint: "getCurrentTeamRanking",
    headers: ["TEAM", "RANKING"],
    dataPath: "data",
    idType: "team",
    itemConfig: {
      name: [""],
      team: ["team_name", "teamName", "name"],
      country: ["team_country", "teamCountry", "country"],
      count: ["ranking", "rank", "position", "count", "total_wins"],
    },
  },
  "best-riders-recent-year": {
    apiEndpoint: "getBestRidersOfRecentYear",
    headers: ["RIDER", "TEAM", "PERFORMANCE"],
    dataPath: "data",
    idType: "rider",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["performance_score", "score", "points", "count", "wins"],
    },
  },
  "oldest-riders": {
    apiEndpoint: "olderstRiders",
    headers: ["NAME", "TEAM", "AGE"],
    dataPath: "data",
    idType: "riders",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["age", "rider_age", "count", "total"],
    },
  },
  "youngest-riders": {
    apiEndpoint: "youngestRiders",
    headers: ["RIDER", "TEAM", "AGE"],
    dataPath: "data",
    idType: "riders",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["age", "rider_age", "count", "total"],
    },
  },
  "victory-ranking": {
    apiEndpoint: "victoryRanking",
    headers: ["RIDER", "TEAM", "VICTORIES"],
    dataPath: "data",
    idType: "riders",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country"],
      count: ["victories", "victory_count", "wins", "count", "total"],
    },
  },

  // ____________Teams slugs___________

  "team-with-most-wins-this-year": {
    apiEndpoint: "TeamWithMostWinsThisYear",
    headers: ["TEAM","WINS"],
    dataPath: "data",
    idType: "teams",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team","teamSlug"],
      country: ["rider_country", "riderCountry", "country","flag"],
      count: [ "wins", "count", "total"],
    },
  },
  "team-ranking": {
    apiEndpoint: "teamRankingCurrentYear",
    headers: ["TEAM", "CLASS","POINTS"],
    dataPath: "data",
    idType: "teams",
    itemConfig: {
      name: ["rider_name", "riderName"],
      team: ["team_name","teamSlug"],
      country: ["rider_country", "riderCountry", "country","flag"],
      count: [ "wins", "count", "points"],
      age: ["class"],
    },
  },
  "oldest-team": {
    apiEndpoint: "OldestTeam",
    headers: ["TEAM","YEAR"],
    dataPath: "data",
    idType: "teams",
    itemConfig: {
      name: ["rider_name", "riderName", "name"],
      team: ["team_name", "teamName", "team","teamSlug"],
      country: ["rider_country", "riderCountry", "country","flag"],
      count: [ "wins", "count", "points","age"],
    },
  },
"amount-of-riders": {
    apiEndpoint: "AmountOfRider",
    headers: ["NAME","AGE"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["rider_name", "riderName", "name","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country","flag"],
      count: [ "wins", "count", "points","riderAge"],
    },
  },
  "rider-with-most-wins-in-team-history": {
    apiEndpoint: "getRiderWithMostWinsInTeamHistory",
    headers: ["NAME","TOTAL"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["rider_name", "riderName", "rider","rider_id","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country_code",],
      count: [ "wins", "count", "points","total"],
    },
  },
  "rider-with-most-classic-wins-in-team-history": {
    apiEndpoint: "getMostClassicWinsForTeam",
    headers: ["NAME","WINS"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["rider_name", "riderName", "rider","riderId","riderSlug"],
      team: ["team_name", "teamName", "team"],
      country: ["rider_country", "riderCountry", "country_code",],
      count: [ "wins", "count", "points","totalClassicWins"],
    },
  },
  "last-victories": {
    apiEndpoint: "getLastVictoriesByTeam",
    headers: ["RACE","CLASS","WINNER"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["race_name"],
      team: ["class"],
      country: ["race_country"],
      count: [ "rider_name"],
    },
  },
  "amount-of-classic-wins": {
    apiEndpoint: "totalClassicWinsByTeam",
    headers: ["RACE","WINNER","YEAR"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["race"],
      team: ["winner","riderSlug"],
      country: ["race_country"],
      count: [ "year"],
    },
  },
  "grand-tour-wins": {
    apiEndpoint: "totalGrandTourWinsByTeam",
    headers: ["RACE","WINNER","YEAR"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["race_name"],
      team: ["rider_name","riderSlug"],
      country: ["race_country"],
      count: [ "year"],
    },
  },
  "current-uci-team-ranking": {
    apiEndpoint: "currentUciTeamRanking",
    headers: ["RACE","RIDER","POINTS"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["race_name",],
      team: ["rider_name","rider_id","riderSlug"],
      country: ["race_country"],
      count: [ "uci_points"],
     
    },
  },
  "last-5-wins": {
    apiEndpoint: "last10WinsByTeam",
    headers: ["RACE","RIDER","YEAR",],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["race_name",],
      team: ["rider_name","rider_id","riderSlug"],
      country: ["race_country"],
      count: [ "year"],
     
    },
  },
  "oldest-rider-under-contract": {
    apiEndpoint: "oldestRiderUnderContract",
    headers: ["RIDER","YEAR",],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["name","rider_id","riderSlug"],
      team: ["rider_name"],
      country: ["nationality"],
      count: [ "age"],
     
    },
  },
  "best-monuments-results": {
    apiEndpoint: "bestMonumentResultsOfTeam",
    headers: ["RIDER","RACE","YEAR"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["rider_name","rider_id","riderSlug"],
      team: ["race"],
      country: ["rider_country"], 
      count: [ "year"],
     
    },
  },
  "rider-longest-with-the-team": {
    apiEndpoint: "RiderWithLongestTeam",
    headers: ["RIDER","YEAR"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["rider_name","riderName","rider_id","riderSlug"],
      team: ["race"],
      country: ["riderCountry"],
      count: [ "yearsWithTeam"],
     
    },
  },
  "last-5-podium-spots": {
    apiEndpoint: "last10PoduimsSpots",
    headers: ["RACE","RIDER","YEAR"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["race_name",],
      team: ["rider_name","rider_id","riderSlug"],
      country: ["race_country"],
      count: [ "race_year"],
    }
  },
  "rider-with-most-races": {
    apiEndpoint: "ridersWithMostRaces",
    headers: ["RIDER","RACES"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["name","rider_id","riderSlug"],
      team: ["rider_name"],
      country: ["nationality"],
      count: [ "total_races"],
    }
  },
  "youngest-rider-under-contract": {
    apiEndpoint: "youngestRiderUnderContract",
    headers: ["RIDER","AGE"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["name","rider_id","riderSlug"],
      team: ["rider_name"],
      country: ["nationality"],
      count: [ "age"],
    }
  },
  "most-successful-race": {
    apiEndpoint: "MostSuccessfulRaces",
    headers: ["RACE","CLASS","WINS"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["race_name",],
      team: ["class","race_id"],
      country: ["country_code"],
      count: [ "total_wins"],
    }
  },
"different-nationalities": {
    apiEndpoint: "DifferentNationalities",
    headers: ["RIDER","AGE"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["name","rider_id","riderSlug"],
      team: ["rider_name"],
      country: ["nationality"],
      count: [ "age"],
    }
  },
"most-top-10-in-races": {
    apiEndpoint: "MostTop10InRaces",
    headers: ["RIDER","COUNT"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["rider_name","rider_id","riderSlug"],
      team: ["team"],
      country: ["rider_country"],
      count: [ "top10_count"],
    }
  },
  "total-wins-per-year": {  
    apiEndpoint: "totalWinsPerYear",
    headers: ["RACE",,"RIDER","CLASS"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["race_name",],
      team: ["rider_name","rider_id","riderSlug"],
      country: ["race_country"],
      count: [ "race_class"],
    }
  },
  "rider-with-most-uci-points": {
    apiEndpoint: "RiderWithMostUciPoints",
    headers: ["RIDER","POINTS"],
    dataPath: "data",
    idType: "teamDetails",
    itemConfig: {
      name: ["rider_name","rider_id","riderSlug"],
      team: ["team"],
      country: ["rider_country"],
      count: [ "total_uci_points"],
    }
  },


};
